import { Data, IProductInput, IUserInput } from '@/types'
import { toSlug } from './utils'

const uniqueStoreId = '7jDf45ff'
const uniqueStoreName = 'Mi super tiendita'

import bcrypt from 'bcryptjs'
const users: IUserInput[] = [
	{
		name: 'Robe',
		email: 'robe@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'Seller',
		storeName: uniqueStoreName,
		storeId: uniqueStoreId,
		isStore: false,
		address: {
			fullName: 'Roberto García',
			street: 'Juan Manuel 1249',
			city: 'Guadalajara',
			province: 'Jal',
			postalCode: '64200',
			country: 'MX',
			phone: '123-456-7890',
		},
		paymentMethod: 'Stripe',
		emailVerified: false,
	},
	{
		name: 'Mario SuperAdmin',
		email: 'mariosuperadmin@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'SuperAdmin',
		storeName: '',
		storeId: '',
		isStore: false,
		address: {
			fullName: 'Mario López',
			street: 'Manuel M. Dieguez 900',
			city: 'Guadalajara',
			province: 'Jal',
			postalCode: '64610',
			country: 'MX',
			phone: '123-456-7890',
		},
		paymentMethod: 'Cash On Delivery',
		emailVerified: false,
	},
	{
		name: 'Mario',
		email: 'mario@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'Admin',
		storeName: uniqueStoreName,
		storeId: uniqueStoreId,
		isStore: false,
		address: {
			fullName: 'Mario López',
			street: 'Manuel M. Dieguez 900',
			city: 'Guadalajara',
			province: 'Jal',
			postalCode: '64610',
			country: 'MX',
			phone: '123-456-7890',
		},
		paymentMethod: 'Cash On Delivery',
		emailVerified: false,
	},
	{
		name: 'Jack',
		email: 'jack@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'Seller',
		storeName: uniqueStoreName,
		storeId: uniqueStoreId,
		isStore: false,
		address: {
			fullName: 'Jack Ryan',
			street: '333 Main St',
			city: 'New York',
			province: 'NY',
			postalCode: '1003',
			country: 'USA',
			phone: '123-456-7890',
		},
		paymentMethod: 'PayPal',
		emailVerified: false,
	}
]

const reviews = [
	{
		rating: 1,
		title: 'Poor quality',
		comment:
			'Very disappointed. The item broke after just a few uses. Not worth the money.',
	},
	{
		rating: 2,
		title: 'Disappointed',
		comment:
			"Not as expected. The material feels cheap, and it didn't fit well. Wouldn't buy again.",
	},
	{
		rating: 2,
		title: 'Needs improvement',
		comment:
			"It looks nice but doesn't perform as expected. Wouldn't recommend without upgrades.",
	},
	{
		rating: 3,
		title: 'not bad',
		comment:
			'This product is decent, the quality is good but it could use some improvements in the details.',
	},
	{
		rating: 3,
		title: 'Okay, not great',
		comment:
			'It works, but not as well as I hoped. Quality is average and lacks some finishing.',
	},
	{
		rating: 3,
		title: 'Good product',
		comment:
			'This product is amazing, I love it! The quality is top notch, the material is comfortable and breathable.',
	},
	{
		rating: 4,
		title: 'Pretty good',
		comment:
			"Solid product! Great value for the price, but there's room for minor improvements.",
	},
	{
		rating: 4,
		title: 'Very satisfied',
		comment:
			'Good product! High quality and worth the price. Would consider buying again.',
	},
	{
		rating: 4,
		title: 'Absolutely love it!',
		comment:
			'Perfect in every way! The quality, design, and comfort exceeded all my expectations.',
	},
	{
		rating: 4,
		title: 'Exceeded expectations!',
		comment:
			'Fantastic product! High quality, feels durable, and performs well. Highly recommend!',
	},
	{
		rating: 5,
		title: 'Perfect purchase!',
		comment:
			"Couldn't be happier with this product. The quality is excellent, and it works flawlessly!",
	},
	{
		rating: 5,
		title: 'Highly recommend',
		comment:
			"Amazing product! Worth every penny, great design, and feels premium. I'm very satisfied.",
	},
	{
		rating: 5,
		title: 'Just what I needed',
		comment:
			'Exactly as described! Quality exceeded my expectations, and it arrived quickly.',
	},
	{
		rating: 5,
		title: 'Excellent choice!',
		comment:
			'This product is outstanding! Everything about it feels top-notch, from material to functionality.',
	},
	{
		rating: 5,
		title: "Couldn't ask for more!",
		comment:
			"Love this product! It's durable, stylish, and works great. Would buy again without hesitation.",
	},
]

const products: IProductInput[] = [
	{
		productId: 1,
		name: 'Cemento Portland Gris 50kg',
		slug: toSlug('Cemento Portland Gris 50kg'),
		category: 'Materiales',
		sku: 'MAT-CEM-001',
		images: [{ imgUrl: 'https://placehold.co/600x400.png?text=Cemento+Portland', imgKey: 'placeholder' }],
		tags: ['best-seller', 'featured'],
		isPublished: true,
		isProductKg: false,
		price: 240.00,
		listPrice: 260.00,
		discountPrice: 0,
		brand: 'Cemex',
		avgRating: 4.8,
		numReviews: 45,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 2 },
			{ rating: 4, count: 10 },
			{ rating: 5, count: 33 },
		],
		numSales: 120,
		countInStock: 500,
		description: 'Cemento Portland gris de alta resistencia, ideal para todo tipo de construcción.',
		reviews: [],
	},
	{
		productId: 2,
		name: 'Cal Hidratada 25kg',
		slug: toSlug('Cal Hidratada 25kg'),
		category: 'Materiales',
		sku: 'MAT-CAL-001',
		images: [{ imgUrl: 'https://placehold.co/600x400.png?text=Cal+Hidratada', imgKey: 'placeholder' }],
		tags: [],
		isPublished: true,
		isProductKg: false,
		price: 75.00,
		listPrice: 85.00,
		discountPrice: 0,
		brand: 'Calidra',
		avgRating: 4.5,
		numReviews: 20,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 1 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 6 },
			{ rating: 5, count: 10 },
		],
		numSales: 80,
		countInStock: 300,
		description: 'Cal hidratada de alta pureza para construcción y estabilización de suelos.',
		reviews: [],
	},
	{
		productId: 3,
		name: 'Pala Cuadrada Puño Y',
		slug: toSlug('Pala Cuadrada Puño Y'),
		category: 'Herramientas',
		sku: 'HER-PAL-001',
		images: [{ imgUrl: 'https://placehold.co/600x400.png?text=Pala+Cuadrada', imgKey: 'placeholder' }],
		tags: ['featured'],
		isPublished: true,
		isProductKg: false,
		price: 150.00,
		listPrice: 180.00,
		discountPrice: 170.00,
		brand: 'Truper',
		avgRating: 4.7,
		numReviews: 15,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 1 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 10 },
		],
		numSales: 45,
		countInStock: 50,
		description: 'Pala cuadrada con mango de madera y puño Y, resistente para trabajo pesado.',
		reviews: [],
	},
	{
		productId: 4,
		name: 'Carretilla 5.5ft3 Neumática',
		slug: toSlug('Carretilla 5.5ft3 Neumática'),
		category: 'Equipo',
		sku: 'EQP-CAR-001',
		images: [{ imgUrl: 'https://placehold.co/600x400.png?text=Carretilla', imgKey: 'placeholder' }],
		tags: ['best-seller'],
		isPublished: true,
		isProductKg: false,
		price: 1100.00,
		listPrice: 1250.00,
		discountPrice: 0,
		brand: 'Truper',
		avgRating: 4.9,
		numReviews: 25,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 2 },
			{ rating: 5, count: 23 },
		],
		numSales: 60,
		countInStock: 20,
		description: 'Carretilla con llanta neumática reforzada, capacidad de 5.5 pies cúbicos.',
		reviews: [],
	},
	{
		productId: 5,
		name: 'Flexómetro 5m',
		slug: toSlug('Flexómetro 5m'),
		category: 'Herramientas',
		sku: 'HER-FLE-001',
		images: [{ imgUrl: 'https://placehold.co/600x400.png?text=Flexometro', imgKey: 'placeholder' }],
		tags: [],
		isPublished: true,
		isProductKg: false,
		price: 80.00,
		listPrice: 95.00,
		discountPrice: 0,
		brand: 'Stanley',
		avgRating: 4.6,
		numReviews: 30,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 2 },
			{ rating: 4, count: 8 },
			{ rating: 5, count: 20 },
		],
		numSales: 150,
		countInStock: 100,
		description: 'Cinta métrica de 5 metros con freno y clip para cinturón.',
		reviews: [],
	},
	{
		productId: 6,
		name: 'Nivel de Aluminio 24"',
		slug: toSlug('Nivel de Aluminio 24"'),
		category: 'Herramientas',
		sku: 'HER-NIV-001',
		images: [{ imgUrl: 'https://placehold.co/600x400.png?text=Nivel+Aluminio', imgKey: 'placeholder' }],
		tags: [],
		isPublished: true,
		isProductKg: false,
		price: 190.00,
		listPrice: 220.00,
		discountPrice: 0,
		brand: 'Truper',
		avgRating: 4.5,
		numReviews: 10,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 1 },
			{ rating: 4, count: 3 },
			{ rating: 5, count: 6 },
		],
		numSales: 25,
		countInStock: 30,
		description: 'Nivel de aluminio de 24 pulgadas con 3 gotas (0, 45 y 90 grados).',
		reviews: [],
	},
	{
		productId: 7,
		name: 'Escalera de Tijera 6 peldaños',
		slug: toSlug('Escalera de Tijera 6 peldaños'),
		category: 'Equipo',
		sku: 'EQP-ESC-001',
		images: [{ imgUrl: 'https://placehold.co/600x400.png?text=Escalera', imgKey: 'placeholder' }],
		tags: ['featured'],
		isPublished: true,
		isProductKg: false,
		price: 1600.00,
		listPrice: 1850.00,
		discountPrice: 0,
		brand: 'Cuprum',
		avgRating: 4.8,
		numReviews: 18,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 3 },
			{ rating: 5, count: 15 },
		],
		numSales: 35,
		countInStock: 15,
		description: 'Escalera de tijera de aluminio con 6 peldaños y tapa portaherramientas.',
		reviews: [],
	},
	{
		productId: 8,
		name: 'Martillo de Uña 16oz',
		slug: toSlug('Martillo de Uña 16oz'),
		category: 'Herramientas',
		sku: 'HER-MAR-001',
		images: [{ imgUrl: 'https://placehold.co/600x400.png?text=Martillo', imgKey: 'placeholder' }],
		tags: [],
		isPublished: true,
		isProductKg: false,
		price: 120.00,
		listPrice: 150.00,
		discountPrice: 0,
		brand: 'Truper',
		avgRating: 4.9,
		numReviews: 40,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 36 },
		],
		numSales: 90,
		countInStock: 80,
		description: 'Martillo de uña curva de 16oz con mango de fibra de vidrio.',
		reviews: [],
	},
	{
		productId: 9,
		name: 'Taladro Rotomartillo 1/2"',
		slug: toSlug('Taladro Rotomartillo 1/2"'),
		category: 'Herramientas Eléctricas',
		sku: 'HER-TAL-001',
		images: [{ imgUrl: 'https://placehold.co/600x400.png?text=Taladro', imgKey: 'placeholder' }],
		tags: ['best-seller', 'featured'],
		isPublished: true,
		isProductKg: false,
		price: 1300.00,
		listPrice: 1450.00,
		discountPrice: 1399.00,
		brand: 'DeWalt',
		avgRating: 4.9,
		numReviews: 55,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 1 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 50 },
		],
		numSales: 75,
		countInStock: 25,
		description: 'Taladro rotomartillo de 1/2 pulgada, velocidad variable y reversible.',
		reviews: [],
	},
	{
		productId: 10,
		name: 'Esmeriladora Angular 4-1/2"',
		slug: toSlug('Esmeriladora Angular 4-1/2"'),
		category: 'Herramientas Eléctricas',
		sku: 'HER-ESM-001',
		images: [{ imgUrl: 'https://placehold.co/600x400.png?text=Esmeriladora', imgKey: 'placeholder' }],
		tags: [],
		isPublished: true,
		isProductKg: false,
		price: 950.00,
		listPrice: 1100.00,
		discountPrice: 0,
		brand: 'Makita',
		avgRating: 4.7,
		numReviews: 22,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 2 },
			{ rating: 4, count: 5 },
			{ rating: 5, count: 15 },
		],
		numSales: 40,
		countInStock: 30,
		description: 'Esmeriladora angular de 4-1/2 pulgadas, potente motor para corte y desbaste.',
		reviews: [],
	},
	{
		productId: 11,
		name: 'Grava Triturada 3/4" (m3)',
		slug: toSlug('Grava Triturada 3/4" (m3)'),
		category: 'Materiales',
		sku: 'MAT-GRA-001',
		images: [{ imgUrl: 'https://placehold.co/600x400.png?text=Grava', imgKey: 'placeholder' }],
		tags: [],
		isPublished: true,
		isProductKg: false,
		price: 600.00,
		listPrice: 650.00,
		discountPrice: 0,
		brand: 'Generico',
		avgRating: 4.5,
		numReviews: 8,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 1 },
			{ rating: 4, count: 2 },
			{ rating: 5, count: 5 },
		],
		numSales: 30,
		countInStock: 100,
		description: 'Grava triturada de 3/4 de pulgada, venta por metro cúbico.',
		reviews: [],
	},
	{
		productId: 12,
		name: 'Yeso Construcción 40kg',
		slug: toSlug('Yeso Construcción 40kg'),
		category: 'Materiales',
		sku: 'MAT-YES-001',
		images: [{ imgUrl: 'https://placehold.co/600x400.png?text=Yeso', imgKey: 'placeholder' }],
		tags: [],
		isPublished: true,
		isProductKg: false,
		price: 120.00,
		listPrice: 140.00,
		discountPrice: 0,
		brand: 'Generico',
		avgRating: 4.6,
		numReviews: 12,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 1 },
			{ rating: 4, count: 3 },
			{ rating: 5, count: 8 },
		],
		numSales: 50,
		countInStock: 200,
		description: 'Yeso para construcción de secado rápido, bulto de 40kg.',
		reviews: [],
	},
]

// crear lista de proveedores 

// crear recepccion de ordenes


const data: Data = {
	headerMenus: [
		{
			name: "Today's Deal",
			href: '/search?tag=todays-deal',
		},
		{
			name: 'New Arrivals',
			href: '/search?tag=new-arrival',
		},
		{
			name: 'Featured Products',
			href: '/search?tag=featured',
		},
		{
			name: 'Best Sellers',
			href: '/search?tag=best-seller',
		},
		{
			name: 'Browsing History',
			href: '/#browsing-history',
		},
		{
			name: 'Customer Service',
			href: '/page/customer-service',
		},
		{
			name: 'About Us',
			href: '/page/about-us',
		},
		{
			name: 'Help',
			href: '/page/help',
		},
	],

	carousels: [
		{
			title: 'Materiales de Construcción',
			description:
				'Todo lo que necesitas para tu obra, desde cimientos hasta acabados.',
			buttonCaption: 'Ver Materiales',
			image: '/images/banner-construction-1.jpg',
			url: '/search?category=Materiales',
			isPublished: true,
		},
		{
			title: 'Herramientas Profesionales',
			description:
				'Equipa a tu equipo con las mejores herramientas del mercado.',
			buttonCaption: 'Ver Herramientas',
			image: '/images/banner-tools-1.jpg',
			url: '/search?category=Herramientas',
			isPublished: true,
		},
		{
			title: 'Ofertas de Temporada',
			description: 'Aprovecha nuestros descuentos en equipos y maquinaria ligera.',
			buttonCaption: 'Ver Ofertas',
			image: '/images/banner-offers-1.jpg',
			url: '/search?tag=todays-deal',
			isPublished: true,
		},
	],
	products,
	users,
	reviews,
}


export default data
